"""add external_ref to transactions

Revision ID: 24a182df71be
Revises: ae7a18d9a093
Create Date: 2026-08-21 12:41:29.340086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a182df71be'
down_revision: Union[str, Sequence[str], None] = 'ae7a18d9a093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('external_ref', sa.String(length=100), nullable=True))
    op.create_index('ix_transactions_user_id_external_ref', 'transactions', ['user_id', 'external_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_id_external_ref', table_name='transactions')
    op.drop_column('transactions', 'external_ref')
    # ### end Alembic commands ###
